#spring.datasource.url=jdbc:mysql://localhost:3306/cser
#spring.datasource.username=root
#pring.datasource.password=root
#postgresql://keerthana:i9VOoyez2qM1queZd2noM6JjiwMFZN2N@
spring.jpa.hibernate.ddl-auto=update
#dpg-d6qitahj16oc73eo25p0-a.oregon-postgres.render.com
#jobportaldb_ogj6
#postgresql://dpg-d6qitahj16oc73eo25p0-a.oregon-postgres.render.com:5432/jobportaldb_ogj6
spring.datasource.url=jdbc:postgresql://dpg-d6qitahj16oc73eo25p0-a.oregon-postgres.render.com:5432/jobportaldb_ogj6
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=keerthana
spring.datasource.password=i9VOoyez2qM1queZd2noM6JjiwMFZN2N
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
